apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: terrayaml.mindcurv.com
  # description: Pass in a set of terrayaml to have it planned and applied if desired
spec:
  scope: Namespaced
  group: mindcurv.com
  versions:
      - name: v1beta1
        served: true
        storage: true
  names:
      kind: TerraYaml
      plural: terrayaml
      singular: terrayaml
      shortNames:
        - ty
        - mc-ty
        - mc-terrayaml
  # preserveUnknownFields: true
  validation:
    openAPIV3Schema:
      required: ["spec"]
      type: object
      properties:
        spec:
          required: ["terrayaml", "apply"]
          type: object
          properties:
            apply:
              type: boolean
              #default: false
            planId:
              type: string
            terrayaml:
              type: string