apiVersion: mindcurv.com/v1beta1
kind: TerraYaml
metadata:
  name: my-ty-example
  team: oss
  environment: testing
  application: wurkflow
  #statefile_region: eu-west-1
spec:
  apply: false
  destroyOnDelete: false
  # planId: ""
  terrayaml: |
    aws:
      s3:
        items:
          - acl: private
            acceleration_status: Enabled
          - bucket: my-bucket-rerere
            acl: private-read
            outputs:
              - name: my-bucket-domain_name
                value: bucket_domain_name
                description: my buckets domain name
      # rds:
      #   version: 2.2
      #   items:
      #     - cluster_identifier: aurora-cluster-demo
      #       engine: aurora-postgresql
      #       availability_zones: ["eu-central-1a", "eu-central-2a"]
      #       database_name: mydb
      #       # master_username: foo
      #       # master_password: bar
      #       backup_retention_period: 5
      # #       preferred_backup_window: 07:00-09:00"
    notify:
      email:
        - ross.crawford@mindcurv.com
        - stefan.schweer@mindcurv.com