apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailcatcher
  labels:
    app: mailcatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailcatcher
  template:
    metadata:
      labels:
        app: mailcatcher
    spec:
      containers:
      - name: mailcatcher
        image: schickling/mailcatcher
        ports:
        - containerPort: 1080
        - containerPort: 1025
---
apiVersion: v1
kind: Service
metadata:
  name: mailcatcher-svc
spec:
  selector:
    app: mailcatcher
  type: NodePort
  ports:
    - protocol: TCP
      port: 1080
      targetPort: 1080